import { WALL_KINDS, ROOF_KINDS, THEMED_BIN_KINDS, type RoofKind, type ThemedBinKind, type WallKind } from './decorationWalls'
/**
 * Zentrale Balancing-Konfiguration.
 *
 * Hier stehen alle Werte, die das Tempo, die Wahrscheinlichkeit oder die
 * Stärke einer Simulation beeinflussen. Geometrie, IDs, Typen und Texte
 * bleiben in ihren jeweiligen Fachmodulen.
 * Welche Config-Gruppe zu welchem System gehört: docs/README.md.
 */
export const SIMULATION_CONFIG = {
  time: {
    speedMultipliers: [0, 1, 3, 8],
    movementSimulationRate: 1,
    normalDayDurationSeconds: 10 * 60,
    startMinute: 8 * 60,
    minutesPerDay: 24 * 60,
    economyIntervalMinutes: 60,
    cashEffectLifetimeSeconds: 1.6,
    fireworkEffectLifetimeSeconds: 2.4,
    uiRefreshIntervalSeconds: 0.1,
    tickSeconds: 0.1,
    commandDelayTicks: 2,
    maxStepsPerFrame: 3,
    hashIntervalTicks: 15,
  },
  economy: {
    decorationWalls: { cost: 30, upkeep: 0, capacity: 0, appeal: 2, defaultPrice: 0 },
    startingMoney: 10_000,
    defaultEntryPrice: 10,
    defaultCampingTicketPrice: 25,
    startingReputation: 50,
    maximumPrice: 1_000_000,
    demolitionRefundRate: 0.25,
    /** Stamp copies charge this share of catalog / way costs (1 = full price). */
    blueprintCopyCostFactor: 0.8,
    treeClearCost: 45,
    emptyParkBaseReputation: 45,
    coasterAppeal: 20,
    coasterAccessCost: 100,
    chainLiftCost: 60,
    buildings: {
      path: { cost: 10, upkeep: 0, capacity: 0, appeal: 0, defaultPrice: 0 },
      food: { cost: 350, upkeep: 12, capacity: 4, appeal: 3, defaultPrice: 12 },
      toilet: { cost: 250, upkeep: 8, capacity: 6, appeal: 1, defaultPrice: 2 },
      ride: { cost: 1200, upkeep: 35, capacity: 12, appeal: 14, defaultPrice: 18 },
      alcohol: { cost: 500, upkeep: 16, capacity: 4, appeal: 5, defaultPrice: 9 },
      mascot: { cost: 380, upkeep: 10, capacity: 4, appeal: 4, defaultPrice: 16 },
      shirt: { cost: 420, upkeep: 12, capacity: 4, appeal: 5, defaultPrice: 18 },
      securityGate: { cost: 900, upkeep: 18, capacity: 1, appeal: 1, defaultPrice: 0 },
      tree: { cost: 55, upkeep: 1, capacity: 0, appeal: 4, defaultPrice: 0 },
      hedge: { cost: 35, upkeep: 1, capacity: 0, appeal: 3, defaultPrice: 0 },
      fence: { cost: 28, upkeep: 0, capacity: 0, appeal: 0, defaultPrice: 0 },
      bench: { cost: 80, upkeep: 1, capacity: 2, appeal: 3, defaultPrice: 0 },
      lighting: { cost: 120, upkeep: 4, capacity: 0, appeal: 5, defaultPrice: 0 },
      lightBalloon: { cost: 280, upkeep: 8, capacity: 0, appeal: 8, defaultPrice: 0 },
      stage: { cost: 2800, upkeep: 95, capacity: 0, appeal: 12, defaultPrice: 0 },
      directionalSpeaker: { cost: 420, upkeep: 12, capacity: 0, appeal: 1, defaultPrice: 0 },
      omniSpeaker: { cost: 620, upkeep: 18, capacity: 0, appeal: 1, defaultPrice: 0 },
      ambulanceGarage: { cost: 5200, upkeep: 120, capacity: 2, appeal: 0, defaultPrice: 0 },
      busStop: { cost: 180, upkeep: 3, capacity: 20, appeal: 0, defaultPrice: 0 },
      busDepot: { cost: 8500, upkeep: 180, capacity: 3, appeal: 0, defaultPrice: 0 },
      wasteDepot: { cost: 3800, upkeep: 80, capacity: 2, appeal: 0, defaultPrice: 0 },
      specialDepot: { cost: 6400, upkeep: 130, capacity: 4, appeal: 0, defaultPrice: 0 },
      wasteBin: { cost: 90, upkeep: 2, capacity: 12, appeal: 1, defaultPrice: 0 },
      sealedWasteContainer: { cost: 480, upkeep: 8, capacity: 80, appeal: 0, defaultPrice: 0 },
      generator: { cost: 2400, upkeep: 55, capacity: 0, appeal: 0, defaultPrice: 0 },
      backupGenerator: { cost: 1600, upkeep: 18, capacity: 0, appeal: 0, defaultPrice: 0 },
      foh: { cost: 1800, upkeep: 28, capacity: 0, appeal: 4, defaultPrice: 0 },
      delayTower: { cost: 980, upkeep: 22, capacity: 0, appeal: 2, defaultPrice: 0 },
      videoWall: { cost: 3200, upkeep: 70, capacity: 0, appeal: 10, defaultPrice: 0 },
      laserShow: { cost: 2600, upkeep: 48, capacity: 0, appeal: 8, defaultPrice: 0 },
      fireworkBattery: { cost: 1400, upkeep: 20, capacity: 0, appeal: 6, defaultPrice: 0 },
      tourBusParking: { cost: 450, upkeep: 6, capacity: 1, appeal: 0, defaultPrice: 0 },
    },
  },
  power: {
    cableCost: 18,
    backupFuelPerHour: 45,
    showFireworkIntervalMinutes: 8,
    showFireworkBurst: 3,
    demand: {
      lighting: 1,
      lightBalloon: 3,
      food: 3,
      alcohol: 2,
      mascot: 2,
      shirt: 2,
      ride: 8,
      securityGate: 2,
      stage: 12,
      directionalSpeaker: 4,
      omniSpeaker: 5,
      foh: 3,
      delayTower: 6,
      videoWall: 8,
      laserShow: 10,
      fireworkBattery: 2,
      ambulanceGarage: 2,
      busDepot: 3,
      wasteDepot: 2,
      specialDepot: 8,
    } as Record<string, number>,
    output: {
      generator: 40,
      backupGenerator: 18,
    } as Record<string, number>,
  },
  visitors: {
    spawnIntervalMinutes:5,
    arrivalsPerIntervalByHour: [
      0.01, 0.01, 0.01, 0.01, 0.02, 0.08,
      0.3, 0.75, 1.45, 1.9, 1.7, 1.45,
      1.2, 1.0, 0.82, 0.66, 0.52, 0.4,
      0.3, 0.21, 0.14, 0.08, 0.04, 0.02,
    ],
    festivalArrivals: {
      leadDayCamperMultiplier: 2.4,
      firstFestivalDayCamperMultiplier: 2.8,
      laterFestivalDayCamperMultiplier: 0.12,
      festivalDayGuestMultiplier: 1,
    },
    budget: 1_000_000,
    walkSpeedMinimum: 0.175,
    walkSpeedRandomRange: 0.335,
    aggressiveProbability: 0.28,
    alcoholDesireMinimum: 25,
    alcoholDesireRandomRange: 60,
    tileOffsetMinimum: 0.1,
    tileOffsetRandomRange: 0.8,
    initialNeeds: {
      hungerMinimum: 70,
      hungerRandomRange: 25,
      toiletMinimum: 75,
      toiletRandomRange: 20,
      funMinimum: 35,
      funRandomRange: 30,
      energyMinimum: 80,
      energyRandomRange: 20,
    },
    movement: {
      baseMultiplier: 2.6924,
      boostMultiplier: 2.8,
      angryMultiplier: 1.2,
      sadMultiplier: 0.72,
      excitedMultiplier: 1.15,
      happyMultiplier: 1.05,
      moderatelyDrunkMultiplier: 0.82,
      veryDrunkMultiplier: 0.62,
      moderatelyDrunkThreshold: 40,
      veryDrunkThreshold: 70,
      evacuationBoostMinutes: 30,
    },
    emotions: {
      angryNeedBelow: 15,
      sadAverageBelow: 45,
      happyAverageAbove: 80,
    },
    decisions: {
      lowEnergy: 16,
      exhaustedEnergy: 3,
      seekToiletBelow: 58,
      seekFoodBelow: 62,
      seekFunBelow: 68,
      seekAlcoholDesire: 65,
      maximumAlcoholForPurchase: 82,
      minimumEnergyForAlcohol: 20,
      seekSouvenirFunBelow: 86,
      seekSouvenirProbability: 0.22,
      socializingFunBelow: 85,
      socializingProbability: 0.32,
      socializingMinutesMinimum: 30,
      socializingMinutesRandomRange: 35,
    },
  },
  needs: {
    hungerDecayPerMinute: 0.05,
    toiletDecayPerMinute: 0.038,
    funDecayPerMinute: 0.032,
    baseEnergyDecayPerMinute: 0.045,
    alcoholEnergyDecayPerMinute: 0.08,
    interactionMinutes: {
      food: 10,
      toilet: 10,
      ride: 24,
      alcohol: 8,
      mascot: 7,
      shirt: 8,
      vomiting: 6,
      stockout: 1.2,
    },
    toilet: { toilet: 100 },
    ride: { fun: 100, energyCost: 8 },
    stationaryConsumption: {
      foodConsumeBelow: 78,
      foodGain: 42,
      foodToiletCost: 9,
      drinkDesireAbove: 55,
      maximumAlcohol: 84,
      alcoholGain: 24,
      drinkFunGain: 8,
      drinkEnergyCost: 2,
      drinkToiletCost: 7,
      cooldownMinimumMinutes: 18,
      cooldownRandomMinutes: 24,
    },
  },
  souvenirs: {
    holdMascotChance: 0.45,
    funGain: 14,
  },
  alcohol: {
    decayPerMinute: 0.06,
    desireGainPerMinute: 0.55,
    drunkBehaviorThreshold: 45,
    veryDrunkBehaviorThreshold: 72,
    passOutThreshold: 70,
    passOutEnergyThreshold: 3,
    streaking: {
      minimumAlcohol: 68,
      maximumAlcohol: 94,
      minimumEnergy: 12,
      chancePerMinute: 0.005,
      durationMinimum: 12.4,
      durationRandomRange: 12.6,
      cooldownMinutes: 180,
      speedMultiplier: 2.2,
      auraRadius: 4,
      nearbyFunPerMinute: 6.5,
      selfFunPerMinute: 3.8,
    },
  },
  nausea: {
    alcoholBaseline: 38,
    alcoholRange: 62,
    toiletBaseline: 55,
    safeCombinationWeight: 0.25,
    toiletCombinationWeight: 1.75,
    gainPerMinute: 1.35,
    safeRecoveryPerMinute: 0.025,
    vomitThreshold: 100,
    resetAfterVomit: 0,
    cooldownMinutes: 90,
    minimumRideAlcohol: 30,
    rideAlcoholScale: 100,
    minimumDrinkAlcohol: 45,
    drinkGainPerAlcoholPoint: 0.7,
    carouselIntensity: 85,
    coasterIntensity: 110,
  },
  incidents: {
    maximumSeverityPerCell: 8,
  },
  logistics: {
    roadBuildCost: 28,
    parkingDesignationCost: 18,
    crosswalkCost: 45,
    markingCost: 4,
    speedZoneCost: 2,
    defaultSpeedLimit: 30 as 10 | 30 | 50,
    worldUnitMeters: 8,
    carArrivalShare: 0.78,
    groupSizeWeights: [0.08, 0.2, 0.27, 0.23, 0.14, 0.08],
    visitorCarCapacity: 6,
    parkingSearchTimeoutMinutes: 24 * 60,
    parkingRetryMinutes: 2,
    parkingRouteCandidateLimit: 8,
    vehicleUnstickMinutes: 6,
    vehicleAbandonMinutes: 22,
    vehicleMoveIntervalMinutes: 0.18,
    pedestrianRoadCostMultiplier: 2,
    crosswalkRoadCostMultiplier: 0.65,
    brakingChanceBySpeed: { 10: 0.98, 30: 0.78, 50: 0.38 },
    ambulanceCost: 2400,
    ambulanceCapacity: 5,
    garbageTruckCost: 3200,
    garbageTruckCapacity: 90,
    sweeperCost: 9800,
    sweeperCapacity: 70,
    sweeperCleanDepth: 2,
    sweeperCleanWidth: 3,
    sweeperMoveIntervalMinutes: 1.35,
    busCost: 1800,
    busResaleFraction: 0.5,
    busCapacity: 40,
    busStopDwellMinutes: 2,
    /** Manhattan tiles from the platform or pull-up road; covers the queue and opposite sidewalk. */
    busBoardingRadiusTiles: 4,
    /** Empty 40-seat bus can fill in one dwell tick; leftover waiters keep the bus after min dwell. */
    busBoardsPerTick: 40,
    busDefaultHeadwayMinutes: 15,
    busMaximumWaitMinutes: 45,
    busPreferenceEnergyThreshold: 42,
    busMinimumJourneyTiles: 10,
    busMinimumWalkSavingsTiles: 3,
    busStopRideCostTiles: 1.5,
    busHeadwayCostDivisor: 6,
    longCampWalkFunLossPerTile: 0.12,
    longCampWalkComplaintTiles: 35,
    trafficLightCost: 120,
    pathBarrierCost: 70,
    accessRerouteMinutes: 8,
  },
  crowding: {
    updateIntervalMinutes: 2,
    ownCellWeight: 1,
    adjacentWeight: 0.5,
    diagonalWeight: 0.25,
    // Isolated tile: 6 people ≈ 30% (still fine), ~9–10 dense, ~13 at 100%.
    peopleBaseline: 3,
    peopleRange: 10,
    visibleThreshold: 0.1,
    pressureStart: 35,
    pressureRange: 65,
    lowNeedThreshold: 20,
    lowEnergyThreshold: 12,
    hungerPressureWeight: 0.45,
    toiletPressureWeight: 0.6,
    energyPressureWeight: 0.35,
    vomitPressure: 0.32,
    maximumBadConditions: 1.5,
    motivationLossPerMinute: 0.028,
    motivationRecoveryPerMinute: 0.014,
    fulfilledNeedsRecoveryPerMinute: 0.042,
    fulfilledNeedThreshold: 62,
    fulfilledEnergyThreshold: 40,
    medicalMotivationRecoveryPerMinute: 0.012,
    denseThreshold: 64,
    crushThreshold: 88,
    crushStress: 62,
    calmThreshold: 22,
    stressGainPerMinute: 0.48,
    stressDecayPerMinute: 7.5,
    panicMinStress: 64,
    panicMinDenseCells: 4,
    panicMinSpreadCells: 3,
    panicMinClusterPeople: 16,
    panicBaseChancePerMinute: 0.000006,
    panicNearbyCap: 28,
    panicNearbyScale: 70,
    panicSpreadChancePerMinute: 0.012,
    panicSpreadMaxChance: 0.036,
    panicNeedLossPerMinute: 1.7,
    panicMotivationLossPerMinute: 1.15,
    panicRecoverMinutes: 6,
    panicFleeBoost: 1.4,
  },
  camping: {
    maximumSharedChairs: 5,
    sharedChairRange: 2,
    pavilionCapacity: 6,
    musicBoxCapacity: 6,
    tentBuildMinutes: 24,
    tentPackMinutes: 18,
    abandonDecayPerMinute: 1.4,
    abandonCollectibleDecay: 8,
    restEnergyPerMinute: 0.22,
    restCompleteEnergy: 72,
    groundSleepEnergyPerMinute: 0.09,
    sleepingHungerDecayPerMinute: 0.02,
    sleepingToiletDecayPerMinute: 0.025,
    wakeAlcoholBelow: 42,
    wakeEnergy: 14,
    socialFunPerMinute: 0.28,
    sleepSchedule: {
      // Festival chronotype: stay up through the night, sleep late morning.
      bedtimeMinimum: 3 * 60,
      bedtimeRandomRange: 3 * 60,
      sleepDurationMinimum: 5 * 60,
      sleepDurationRandomRange: 4 * 60,
      scheduledSleepEnergyBelow: 80,
      nonCamperDepartureEnergyBelow: 28,
      familyBedtimeAdvanceMinutes: 150,
      peakAlertStart: 16 * 60,
      peakAlertEnd: 2 * 60,
      peakEnergyDecayMultiplier: 0.58,
      afterBedtimeEnergyDecayMultiplier: 1.65,
      legacyCivilianBedtimeFrom: 20 * 60,
      legacyCivilianBedtimeUntil: 24 * 60,
      legacyBedtimeShiftMinutes: 6 * 60,
      legacyWakeShiftMinutes: 5 * 60,
      legacyFamilyHourBedtime: 21,
    },
    unplacedWaitMaximumMinutes: 24 * 60,
    unplacedRetryIntervalMinutes: 30,
    unplacedMotivationLossPerMinute: 0.025,
    siteSelection: {
      beautyWeight: 1.35,
      partyWeight: 1.35,
      freeCampingNeighborWeight: 4.2,
      adjacentTentPenalty: 14,
      nearbyTentPenalty: 5,
      nearbyTentRadius: 2,
      distancePenalty: 0.12,
      scoreJitter: 2.4,
      pathfindLimit: 18,
    },
  },
  dayNight: {
    sunriseMinute: 6 * 60,
    sunsetMinute: 21 * 60,
    twilightMinutes: 75,
    minimumAmbientIntensity: 0.35,
    maximumAmbientIntensity: 1.65,
    maximumSunIntensity: 2.4,
    nightLightEmissiveIntensity: 1.8,
  },
  inventory: {
    tent: { spawnProbability: 0.68, detectionDifficulty: 0.05 },
    chairs: { spawnProbability: 0.62, detectionDifficulty: 0.08 },
    pavilion: { spawnProbability: 0.24, detectionDifficulty: 0.04 },
    musicBox: { spawnProbability: 0.32, detectionDifficulty: 0.12 },
    alcohol: { spawnProbability: 0.72, detectionDifficulty: 0.35 },
    food: { spawnProbability: 0.65, detectionDifficulty: 0.2 },
    fireworks: { spawnProbability: 0.14, detectionDifficulty: 0.65 },
    maximumAlcoholExtraQuantity: 3,
    maximumFoodExtraQuantity: 2,
    maximumFireworksExtraQuantity: 2,
  },
  fireworks: {
    launchRatePerGameMinute: 0.0012,
    minimumLaunchAlcohol: 35,
    minimumFireRiskAlcohol: 55,
    fireProbabilityAtMaximumAlcohol: 0.025,
    funGain: 12,
    emotionMinutes: 35,
    fireSeverity: 1.4,
  },
  staff: {
    roles: {
      // Walk +15% vs 0.29; loaded trips still apply waste.cleanerCarrySpeedMultiplier.
      cleaner: { hireCost: 180, hourlyWage: 14, speed: 0.334 },
      security: { hireCost: 260, hourlyWage: 22, speed: 0.295 },
      firefighter: { hireCost: 320, hourlyWage: 26, speed: 0.2 },
      medic: { hireCost: 300, hourlyWage: 25, speed: 0.2 },
    },
    // Slightly shorter jobs so bag pickup/empty keep pace with the faster walk.
    cleanerWorkMinutes: 9,
    cleanerLitterWorkMinutes: 3.5,
    cleanerBinWorkMinutes: 5.5,
    firefighterWorkMinutes: 16,
    medicNauseaThreshold: 85,
  },
  medical: {
    bedsPerCell: 3,
    alcoholDecayPerMinute: 0.18,
    nauseaRecoveryPerMinute: 0.3,
    energyRecoveryPerMinute: 0.28,
    motivationRecoveryPerMinute: 0.02,
    dischargeAlcoholBelow: 35,
    dischargeEnergy: 38,
  },
  security: {
    defaultThoroughness: 0.5,
    maximumDetectionChance: 0.98,
    baseDetectionChance: 0.12,
    thoroughnessDetectionWeight: 0.88,
    difficultyWeight: 0.7,
    baseDurationMinutes: 2,
    additionalDurationMinutes: 10,
    baseFunPenalty: 2,
    additionalFunPenalty: 7,
    baseMotivationPenalty: 1,
    additionalMotivationPenalty: 5,
  },
  pathfinding: {
    crowdingCostWeight: 0.2,
    incidentCost: 0.45,
    unattractiveCostWeight: 0.35,
    grassCostMultiplier: 2.8,
    parkingCostMultiplier: 2.2,
    maxFacilityCandidates: 8,
    maxScoredPathChecks: 4,
    wanderMinSteps: 8,
    wanderMaxSteps: 14,
    exploreSearchEvery: 3,
    pathCacheLimit: 3072,
    pathCacheLifetimeTicks: 30,
    decisionsPerTick: 16,
  },
  atmosphere: {
    updateIntervalMinutes: 2,
    diminishingSaturation: 24,
    visibleThreshold: 1,
    preferenceMinimum: 0.15,
    preferenceRandomRange: 0.85,
    sources: {
      ...Object.fromEntries([...WALL_KINDS, ...ROOF_KINDS, ...THEMED_BIN_KINDS].map(kind => [kind, { beauty: 2, party: 0, range: 1 }])) as Record<WallKind | RoofKind | ThemedBinKind, { beauty: number; party: number; range: number }>,
      bunting: { beauty: 8, party: 2, range: 3 },
      stringLights: { beauty: 10, party: 3, range: 3 },
      hayBale: { beauty: 4, party: 0, range: 2 },
      parasol: { beauty: 8, party: 0, range: 3 },
      picnicTable: { beauty: 7, party: 1, range: 2 },
      festivalSign: { beauty: 5, party: 0, range: 2 },
      shrub: { beauty: 7, party: 0, range: 2 },
      flowerbed: { beauty: 9, party: 0, range: 2 },
      planter: { beauty: 9, party: 0, range: 2 },
      rock: { beauty: 5, party: 0, range: 2 },
      statue: { beauty: 15, party: 0, range: 3 },
      banner: { beauty: 7, party: 1, range: 2 },
      tree: { beauty: 11, party: 0, range: 4 },
      hedge: { beauty: 8, party: 0, range: 3 },
      fence: { beauty: -3, party: 0, range: 1 },
      bench: { beauty: 6, party: 0, range: 2 },
      lighting: { beauty: 10, party: 0, range: 4 },
      lightBalloon: { beauty: 14, party: 1, range: 8 },
      totem: { beauty: 12, party: 2, range: 3 },
      flagPole: { beauty: 8, party: 1, range: 3 },
      lanternPole: { beauty: 9, party: 2, range: 3 },
      kegStack: { beauty: 5, party: 3, range: 2 },
      inflatable: { beauty: 10, party: 4, range: 3 },
      prayerFlags: { beauty: 9, party: 1, range: 3 },
      fireBowl: { beauty: 8, party: 3, range: 2 },
      picketFence: { beauty: 5, party: 0, range: 2 },
      ropeFence: { beauty: 3, party: 0, range: 1 },
      streamers: { beauty: 5, party: 2, range: 2 },
      trafficCone: { beauty: 2, party: 0, range: 1 },
      crateStack: { beauty: 3, party: 0, range: 1 },
      oilDrum: { beauty: 3, party: 1, range: 1 },
      pinwheel: { beauty: 4, party: 1, range: 2 },
      windSock: { beauty: 4, party: 0, range: 2 },
      hangingBasket: { beauty: 8, party: 0, range: 2 },
      cactusPot: { beauty: 6, party: 0, range: 2 },
      gnome: { beauty: 8, party: 0, range: 2 },
      windChimes: { beauty: 7, party: 1, range: 2 },
      chalkboard: { beauty: 5, party: 0, range: 2 },
      loungeChair: { beauty: 7, party: 1, range: 2 },
      beanBag: { beauty: 6, party: 1, range: 2 },
      tikiTorch: { beauty: 7, party: 3, range: 2 },
      decoSpeaker: { beauty: 4, party: 5, range: 3 },
      boombox: { beauty: 5, party: 6, range: 3 },
      photoFrame: { beauty: 11, party: 2, range: 3 },
      discoBall: { beauty: 12, party: 5, range: 3 },
      inflatableCactus: { beauty: 10, party: 3, range: 3 },
      giantMushroom: { beauty: 14, party: 2, range: 3 },
      crystalTotem: { beauty: 16, party: 1, range: 4 },
      welcomeArch: { beauty: 18, party: 3, range: 4 },
      desertPalm: { beauty: 8, party: 0, range: 3 },
      dustLantern: { beauty: 7, party: 2, range: 2 },
      playaTotem: { beauty: 13, party: 1, range: 3 },
      tumbleweed: { beauty: 3, party: 0, range: 1 },
      forestFern: { beauty: 8, party: 0, range: 2 },
      mossLog: { beauty: 6, party: 0, range: 2 },
      foxfireLamp: { beauty: 10, party: 3, range: 3 },
      woodlandIdol: { beauty: 13, party: 1, range: 3 },
      neonPlant: { beauty: 7, party: 3, range: 2 },
      neonArch: { beauty: 15, party: 5, range: 4 },
      uvSpeaker: { beauty: 5, party: 6, range: 3 },
      glowTape: { beauty: 6, party: 3, range: 2 },
      scrapPlanter: { beauty: 5, party: 0, range: 2 },
      palletBench: { beauty: 5, party: 1, range: 2 },
      workLamp: { beauty: 6, party: 2, range: 2 },
      chainFence: { beauty: 2, party: 0, range: 1 },
      palmTree: { beauty: 10, party: 0, range: 3 },
      tikiStool: { beauty: 5, party: 1, range: 2 },
      tikiMask: { beauty: 11, party: 2, range: 3 },
      coconutPile: { beauty: 4, party: 0, range: 1 },
      altarTable: { beauty: 9, party: 1, range: 2 },
      spiritLantern: { beauty: 10, party: 2, range: 3 },
      runeStone: { beauty: 12, party: 1, range: 3 },
      occultBanner: { beauty: 8, party: 1, range: 2 },
      circusStool: { beauty: 5, party: 2, range: 2 },
      carnivalBulbs: { beauty: 10, party: 4, range: 3 },
      miniBigTop: { beauty: 14, party: 4, range: 3 },
      popcornCart: { beauty: 8, party: 3, range: 2 },
      alpineFir: { beauty: 11, party: 0, range: 3 },
      beerGardenTable: { beauty: 7, party: 2, range: 2 },
      beerLantern: { beauty: 8, party: 2, range: 2 },
      maypole: { beauty: 16, party: 3, range: 4 },
      icePine: { beauty: 10, party: 0, range: 3 },
      iceBench: { beauty: 6, party: 0, range: 2 },
      auroraLamp: { beauty: 13, party: 3, range: 3 },
      iceSculpture: { beauty: 15, party: 1, range: 4 },
      snowman: { beauty: 9, party: 1, range: 2 },
      iceFence: { beauty: 5, party: 0, range: 2 },
      copperPlanter: { beauty: 7, party: 0, range: 2 },
      gearBench: { beauty: 6, party: 1, range: 2 },
      gasLamp: { beauty: 9, party: 2, range: 3 },
      pipeTotem: { beauty: 14, party: 2, range: 3 },
      gearStack: { beauty: 5, party: 1, range: 1 },
      pipeRail: { beauty: 3, party: 0, range: 1 },
      stage: { beauty: 5, party: 36, range: 10 },
      directionalSpeaker: { beauty: 0, party: 17, range: 7 },
      omniSpeaker: { beauty: -1, party: 11, range: 5 },
      delayTower: { beauty: -1, party: 15, range: 8 },
      videoWall: { beauty: 8, party: 16, range: 6 },
      laserShow: { beauty: 3, party: 28, range: 8 },
      fireworkBattery: { beauty: 2, party: 10, range: 5 },
      foh: { beauty: 3, party: 2, range: 2 },
      generator: { beauty: -8, party: -2, range: 3 },
      backupGenerator: { beauty: -6, party: -1, range: 2 },
      dancer: { beauty: 0, party: 2.4, range: 2 },
      campConversation: { beauty: 0, party: 1.5, range: 2 },
      campMusicBox: { beauty: 1, party: 7, range: 3 },
      vomit: { beauty: -14, party: -2, range: 2 },
      litter: { beauty: -8, party: -1, range: 2 },
      wasteDump: { beauty: -48, party: -10, range: 6 },
      wasteBin: { beauty: 2, party: 0, range: 2 },
      // Sealed dumpsters smell and look far less than open dumps/bags.
      sealedWasteContainer: { beauty: -8, party: -2, range: 3 },
      fire: { beauty: -22, party: -8, range: 3 },
      sleeper: { beauty: -9, party: -3, range: 2 },
      sweeperNoise: { beauty: -6, party: -2, range: 3 },
    },
    directionalSpeakerTooLoud: -18,
    directionalSpeakerPositiveStart: 2,
    forecourtCapacityPerCell: 9,
    forecourtDesignationCost: 8,
    partyDestinationMinimumMood: 18,
    partyDecisionProbability: 0.52,
    stagePerformanceMinutes: 60,
    stageBreakMinutes: 30,
    partyDurationMinimum: 35,
    partyDurationRandomRange: 55,
    concertArriveEarlyMinutes: 30,
    // Live booked set only; waiting / idle / dark stages do not refill Festivallust.
    concertMotivationPerMinute: 0.42,
    concertToplessChancePerMinute: 0.002,
    concertToplessNearbyFun: 5.5,
    concertToplessSelfFun: 2.2,
    concertToplessRadius: 5,
    bungeeNudeChance: 0.02,
    partyFunPerMinute: 0.9,
    dancingFunBonusPerMinute: 0.4,
    partyEnergyCostPerMinute: 0.045,
    danceMoodThreshold: 30,
    dancePreferenceThreshold: 0.3,
    danceFloorMoodThreshold: 8,
    danceFloorPreferenceThreshold: 0.08,
    danceFloorCrowdingScale: 0.4,
    danceFloorOvercrowdingStart: 92,
    danceFloorAnglePenalty: 6,
    concertSpreadGoals: 4,
    hotspotCapacity: 4,
    forecourtScoreBonus: 90,
    partyPreferenceDecisionWeight: 0.7,
    occupancyScorePenalty: 8,
    distanceScorePenalty: 1.1,
    crowdingScorePenalty: 0.35,
    preferenceDeficitThreshold: 28,
    preferenceMotivationLossPerMinute: 0.018,
    preferenceFunLossPerMinute: 0.012,
    overcrowdingStart: 75,
    overcrowdingMotivationLossPerMinute: 0.035,
    benchRestEnergyThreshold: 35,
    benchRestEnergyPerMinute: 0.35,
    benchRestMinutes: 60,
    benchCapacity: 2,
    leisureMinimumFieldValue: 8,
    leisureCapacityPerPathCell: 5,
    leisureDurationMinimum: 45,
    leisureDurationRandomRange: 75,
    leisureFunPerMinute: 0.08,
    conversationFunPerMinute: 0.12,
    leisureDecisionDistancePenalty: 0.85,
  },
  coasters: {
    boardingMinutesPerPerson: 0.4,
    defaultDispatchIntervalMinutes: 30,
    minimumDispatchIntervalMinutes: 5,
    maximumDispatchIntervalMinutes: 120,
    queueSlotsPerCell: 6,
    queueSlotColumns: 3,
    // Wartende Gäste rücken fast sofort nach, sobald vorn jemand in die Attraktion geht.
    queueMovementPerMinute: 2.8,
    queueSlotOffset: 0.2,
    fullQueueAvoidanceMinutes: 120,
    paymentAvoidanceMinutes: 180,
    recallAvoidanceMinutes: 60,
    rideEnergyCost: 10,
    trackPieceCosts: {
      station: 450,
      straight: 80,
      slopeGentleUp: 115,
      slopeUp: 130,
      slopeGentleDown: 105,
      slopeDown: 110,
      pitchTransition: 125,
      bankTransition: 120,
      curveLeft1: 110,
      curveRight1: 110,
      curveLeft2: 150,
      curveRight2: 150,
      curveLeft3: 190,
      curveRight3: 190,
      curveLeft4: 230,
      curveRight4: 230,
      helixLeft: 320,
      helixRight: 320,
    },
    // Derived at mesh/path build time; snapshot pieces stay sharp. Modest only.
    // Horizontal curves stay circular in plan; sigma only blends elevation / non-curve joins.
    trackJoinSmoothing: {
      sigma: 0.28,
    },
    classicSteel: {
      carCapacity: 4,
      defaultTicketPrice: 20,
      physics: {
        worldUnitMeters: 8,
        carMassKg: 480,
        passengerMassKg: 75,
        rollingResistance: 0.008,
        dragArea: 0.53,
        // m/s: ~60% faster circuits vs 0.1.160; gravity stays 9.81.
        stationLaunchSpeed: 22.4,
        stationDriveSpeed: 6.72,
        chainSpeed: 10.4,
        carSpacing: 0.68,
      },
    },
    physicsSimulation: {
      integrationStepSeconds: 0.04,
      gravity: 9.81,
      airDensity: 1.225,
      chainAccelerationFactor: 2.5,
      stationApproachBufferMeters: 4,
      stationBrakingDeceleration: 4.2,
      stationBrakingBufferMeters: 1,
      stationDriveAccelerationLimit: 9.6,
      stationDriveResponse: 3.5,
      endBrakeDistanceMeters: 8,
      endBrakeDeceleration: 5.8,
      minimumSpeed: -20,
      maximumSpeed: 90,
      stationStopSpeed: 0.5,
      stationStopDistanceMeters: 0.08,
      stationOvershootDistance: 0.001,
      stationOvershootDamping: 0.5,
    },
  },
  terrain: {
    minHeight: -4,
    maxHeight: 6,
    // Water plane sits a half-step below land-at-0 so shores show a drop.
    waterHeight: -0.5,
    heightStep: 0.5,
    maxSlope: 0.5,
    mudHeight: -1,
    editCost: 8,
    mudMoveMultiplier: 0.28,
    mudPathCostMultiplier: 7.2,
    mudPavedCostMultiplier: 2.6,
    minSwimDepth: 0.5,
    swimMoveMultiplier: 0.42,
    swimPathCostMultiplier: 4.6,
    swimFunPerMinute: 0.14,
    swimDurationMinimum: 40,
    swimDurationRandomRange: 55,
    swimCapacityPerCell: 6,
    swimDecisionDistancePenalty: 0.7,
    treeDensity: 0.042,
  },
  bandSupply: {
    bareStageAttractiveness: 22,
    satisfactionBarePenalty: 28,
    bareShowQuality: 0.62,
    maxShowQuality: 1.18,
    satisfactionFromAttractiveness: 0.45,
    satisfactionFromCatering: 0.40,
    parkingFullAttractivenessBonus: 28,
    cateringRange: 12,
    cateringPerFoodStall: 18,
    cateringPerDrinkStall: 10,
    cateringCap: 100,
    visitorArrivalDrawBelow: 30,
    busArriveHour: 8,
    busDepartHour: 23,
    backstageDesignationCost: 8,
    tipPerWatcherMinute: 0.08,
    fanIntrusionRange: 6,
    fanIntrusionChancePerMinute: 0.035,
    fanAttractivenessPenaltyPerFan: 6,
    fanAttractivenessPenaltyCap: 36,
    fanLingerMinutes: 4,
  },
  waste: {
    dumpDesignationCost: 15,
    dumpCapacity: 180,
    dumpFullRatio: 0.9,
    dumpStoredBeautyPerBag: -1.4,
    sealedContainerCapacity: 80,
    // Open dump bags are -1.4 each; a sealed lid is about 1/6th of that.
    sealedContainerStoredBeautyPerBag: -0.22,
    tentPackLitterChance: 0.62,
    binRange: 7,
    binCapacity: 12,
    // Nearest bin in binRange is full or unusable: drop litter here, do not hunt farther.
    visitorDropIfBinFull: true,
    binFullBeauty: -12,
    cleanerCarrySpeedMultiplier: 0.62,
    cleanerMaxCarry: 12,
    cleanerTripCarry: 3,
    // Idle cleaners empty bins at/above this fill (25% of capacity). Full bins stay urgent.
    cleanerIdleEmptyFill: 3,
    truckDispatchThreshold: 1,
    truckLoadMinutes: 6,
    truckUnloadMinutes: 4,
  },
  ticker: {
    dumpFullRepeatMinutes: 45,
    incidentRepeatMinutes: 15,
    historyLimit: 24,
  },
  queues: {
    // Stall queues only: half the tile width is the wait lane, half the return lane.
    stallLaneOffset: 0.22,
    inboundSlotColumns: 2,
    inboundSlotOffset: 0.12,
    alongJitter: 0.16,
  },
  /**
   * Camera-listener festival SFX. Values are sim-tick / world units, not wall-clock.
   * Playback may use real time; what can emit is decided here and in `src/game/audio.ts`.
   */
  audio: {
    maxOneShotVoices: 12,
    maxAmbientVoices: 6,
    maxDistance: 28,
    refDistance: 6,
    rolloff: 1.2,
    clusterSize: 4,
    waterSampleStep: 3,
    cheerMinCluster: 6,
    crowdMinCluster: 4,
    screamSpeed: 10,
    masterGain: 0.28,
    cooldownTicks: {
      placeBuilding: 0,
      demolish: 0,
      coasterLaunch: 8,
      cheer: 20,
      scream: 16,
      medical: 12,
      busHiss: 15,
      wasteTruck: 15,
      incident: 10,
      uiClick: 2,
    },
  },
} as const

