import assert from 'node:assert/strict'
import { MeshStandardMaterial, Vector3 } from 'three'
import { FacadeReveal } from '../src/view/facadeReveal'

export function testFacadeReveal(): void {
  const source = new MeshStandardMaterial()
  const reveal = new FacadeReveal(source)
  const other = new FacadeReveal(source)
  reveal.update(0)
  reveal.setTarget(new Vector3(2, 1, 3))
  reveal.update(50)
  assert.ok(reveal.strength.value > 0 && reveal.strength.value < 1)
  assert.equal(reveal.material.depthWrite, false)
  assert.equal(source.transparent, false)
  assert.equal(other.strength.value, 0, 'hover state must remain view-local')
  reveal.setTarget(new Vector3(8, 1, 3))
  reveal.update(100)
  assert.ok(reveal.center.value.x > 2 && reveal.center.value.x < 8, 'center moves smoothly')
  for (let t = 150; t <= 1000; t += 50) reveal.update(t)
  assert.ok(reveal.strength.value > .99)
  assert.equal(reveal.isClickThrough(new Vector3(8, 4, 3)), true, 'faded roof permits picking below it')
  assert.equal(reveal.isClickThrough(new Vector3(12, 4, 3)), false, 'distant facades remain solid')
  reveal.setTarget(null)
  reveal.update(1050)
  assert.ok(reveal.strength.value > 0 && reveal.strength.value < .99)
  for (let t = 1100; t <= 2200; t += 50) reveal.update(t)
  assert.equal(reveal.strength.value, 0)
  assert.equal(reveal.material.depthWrite, true)
  reveal.setTarget(new Vector3(8, 1, 3))
  reveal.update(2250)
  reveal.reset()
  assert.equal(reveal.strength.value, 0, 'decoration mode restores opacity immediately')
  assert.equal(reveal.isClickThrough(new Vector3(8, 1, 3)), false)
  reveal.update(2300)
  assert.equal(reveal.strength.value, 0, 'reset cancels the hover target')
  reveal.material.dispose()
  other.material.dispose()
  source.dispose()
  console.log('PASS facade reveal: smooth transitions and independent view state')
}
