import type { GameSnapshot } from './game/GameState'
import { BANDS, bandGenreLabel, bandStarRating, bookingHoursOpen, festivalTime, isFiveStarBand, showIssue, type FestivalAction } from './game/festivalManagement'
import { GENRES, bandGenre, genreAffinity, normalizeMusic, expectedMusicMix, lineupMix, type MusicMix } from './game/musicTaste'
import { formatMoney, formatNumber, formatPercent, joinList, joinParts, localize, localizeName, t } from './i18n'
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const clock=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`
const DAY_MINUTES=1440,SLOT_MINUTES=30,SLOT_COUNT=DAY_MINUTES/SLOT_MINUTES
/** A share (0–1) as a percentage with at most one decimal: `12,5 %`. */
const share=(value:number)=>formatPercent(Math.round(value*1000)/10)
/** A stage's own design name (a canonical default or the player's), else its place in the line-up. */
const stageName=(stage:{stageDesign?:{name:string}},index:number)=>stage.stageDesign?.name?localizeName(stage.stageDesign.name):t`Bühne ${index+1}`
function legendEntry(genre:typeof GENRES[number],expected:MusicMix,base:MusicMix,previous:MusicMix|null){
  const delta=previous?`${base[genre.id]>=previous[genre.id]?'+':''}${formatNumber(Math.round((base[genre.id]-previous[genre.id])*1000)/10)}`:''
  return `<div><i style="background:${genre.color}"></i><strong>${genre.name}</strong><span>${t`${share(expected[genre.id])} erwartet`}</span><small>${joinParts(t`Basis ${share(base[genre.id])}`,previous&&t`${delta} Pp.`)}</small></div>`
}
function wheel(mix:MusicMix,label:string){
  let start=-Math.PI/2
  const slices=GENRES.map(g=>{const angle=mix[g.id]*Math.PI*2,end=start+Math.min(angle,Math.PI*2-.00001),r=84,inner=49,point=(a:number,r:number)=>`${110+Math.cos(a)*r},${110+Math.sin(a)*r}`;const path=`M${point(start,r)} A${r},${r} 0 ${angle>Math.PI?1:0} 1 ${point(end,r)} L${point(end,inner)} A${inner},${inner} 0 ${angle>Math.PI?1:0} 0 ${point(start,inner)} Z`;start=end;return angle>0?`<path d="${path}" fill="${g.color}" stroke="#203a31" stroke-width="2"><title>${g.name}: ${share(mix[g.id])}</title></path>`:''}).join('')
  return `<figure class="music-wheel"><svg viewBox="0 0 220 220" role="img" aria-label="${label}: ${joinList(GENRES.map(g=>t`${g.name} ${Math.round(mix[g.id]*100)} Prozent`))}">${slices}<text x="110" y="107" text-anchor="middle" fill="#f1eedb" font-size="16">${t('8 Genres')}</text><text x="110" y="126" text-anchor="middle" fill="#b2c6ba" font-size="10">${label}</text></svg><figcaption>${label}</figcaption></figure>`
}
export function musicOverview(s:Readonly<GameSnapshot>){const f=s.festival,base=normalizeMusic(f.musicBase),expected=expectedMusicMix(f),program=lineupMix(f),previous=normalizeMusic(f.previousMusicBase??f.musicBase)
  return `<article class="music-overview"><h3>${joinParts(t('Musikalische Identität'),t`Ausgabe ${f.edition+(f.enabled?0:1)}`)}</h3><div class="music-wheels">${wheel(base,t('Besucherbasis'))}${wheel(expected,t('Erwartete Gäste'))}${f.bookings.length?wheel(program,t('Programmanteile')):`<p>${t('Noch kein Programm. Alle acht Musikrichtungen starten gleich stark.')}</p>`}</div><div class="music-legend">${GENRES.map(g=>legendEntry(g,expected,base,f.previousMusicBase?previous:null)).join('')}</div><p>${t('Farbreihenfolge: ähnliche Musikrichtungen liegen nebeneinander. Die Prognose mischt 75 % Besucherbasis und 25 % Programm (Spielminuten). Erfolgreich gespielte Genres prägen bis zu 20 % der Basis für die nächste Ausgabe; abgesagte Auftritte zählen nicht. Anreisen bleiben durch Nachfrage und Tickets begrenzt.')}</p></article>`
}
export function mountMusicPlanner(root:HTMLElement,getSnapshot:()=>Readonly<GameSnapshot>,execute:(a:FestivalAction)=>void,toast:(s:string,error?:boolean)=>void){
  let day=0,duration=90,selected='meadow',moving='',dragging=false,fingerprint='',selectChanged=false,starTab=0,minAutoStars=1,maxAutoStars=5
  const issue=(s:Readonly<GameSnapshot>,stageId:string,start:number)=>{
    const booking=s.festival.bookings.find(b=>b.id===moving),band=BANDS.find(b=>b.id===(booking?.bandId??selected))!,length=booking?.duration??duration
    if(s.festival.finished)return t('Nächste Ausgabe zuerst vorbereiten')
    if(day*1440+start<=festivalTime(s))return t('Dieser Zeitpunkt liegt in der Vergangenheit')
    if(start+length>1440||!bookingHoursOpen(s,start,length))return t('Bühnen laut Tagesplanung geschlossen')
    if(s.festival.bookings.some(b=>b.id!==moving&&b.day===day&&(b.bandId===band.id||(b.stageId===stageId&&start<b.start+b.duration+30&&start+length+30>b.start))))return t('Band schon gebucht oder Bühne inklusive Umbauzeit belegt')
    if(s.festival.reputation.music<band.reputation)return t`Musikruf ${band.reputation} erforderlich`
    if(!moving&&s.money<band.fee)return t('Nicht genug Geld für die Gage')
    return ''
  }
  const commit=(target:HTMLElement)=>{const s=getSnapshot(),stageId=target.dataset.slot!,start=Number(target.dataset.start),error=issue(s,stageId,start);if(error){toast(error,true);return}const booking=s.festival.bookings.find(b=>b.id===moving);if(booking)execute({type:'moveBooking',id:moving,stageId,day,start,duration:booking.duration});else execute({type:'book',bandId:selected,stageId,day,start,duration});moving='';fingerprint='';render(getSnapshot())}
  let pointer:{id:number;x:number;y:number;band:string;booking:string}|null=null,suppressClick=false
  root.addEventListener('pointerdown',e=>{const card=(e.target as Element).closest<HTMLElement>('[data-band-card],[data-booking-card]');if(!card||e.button!==0||(card as HTMLButtonElement).disabled)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,band:card.dataset.bandCard??'',booking:card.dataset.bookingCard??''}})
  root.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId||Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)<6)return;dragging=true;selected=pointer.band||selected;moving=pointer.booking;root.setPointerCapture(e.pointerId);root.querySelectorAll('.drop-good,.drop-bad').forEach(el=>el.classList.remove('drop-good','drop-bad'));const slot=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-slot]');if(slot&&root.contains(slot))slot.classList.add(issue(getSnapshot(),slot.dataset.slot!,Number(slot.dataset.start))?'drop-bad':'drop-good')})
  root.addEventListener('pointerup',e=>{const wasDragging=dragging;if(pointer&&pointer.id===e.pointerId){pointer=null;if(root.hasPointerCapture(e.pointerId))root.releasePointerCapture(e.pointerId);if(wasDragging){dragging=false;suppressClick=true;setTimeout(()=>suppressClick=false,0);const slot=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-slot]');if(slot&&root.contains(slot))commit(slot);else{fingerprint='';render(getSnapshot())}}}})
  root.addEventListener('pointercancel',()=>{pointer=null;dragging=false;fingerprint='';render(getSnapshot())})
  root.addEventListener('click',e=>{if(suppressClick)return;const target=(e.target as Element).closest<HTMLElement>('[data-band-card],[data-slot],[data-booking-card],[data-cancel-move],[data-cancel-booking],[data-auto-lineup],[data-star-tab],[data-plan-day-chip]');if(!target)return;if(target.hasAttribute('data-auto-lineup')){execute({type:'autoLineup',duration,minStars:minAutoStars,maxStars:maxAutoStars});moving='';fingerprint='';render(getSnapshot());return}if(target.dataset.starTab){starTab=Number(target.dataset.starTab);fingerprint='';render(getSnapshot());return}if(target.dataset.planDayChip){day=Number(target.dataset.planDayChip);moving='';fingerprint='';render(getSnapshot());return}if(target.dataset.bandCard){selected=target.dataset.bandCard;moving='';fingerprint='';render(getSnapshot())}else if(target.dataset.bookingCard){moving=target.dataset.bookingCard;fingerprint='';render(getSnapshot())}else if(target.hasAttribute('data-cancel-move')){moving='';fingerprint='';render(getSnapshot())}else if(target.dataset.cancelBooking){execute({type:'cancel',id:target.dataset.cancelBooking});moving='';fingerprint='';render(getSnapshot())}else if(target.dataset.slot)commit(target)})
  root.addEventListener('change',e=>{const input=e.target as HTMLSelectElement;if(input.matches('[data-plan-duration]'))duration=Number(input.value);if(input.matches('[data-auto-min-stars]'))minAutoStars=Number(input.value);if(input.matches('[data-auto-max-stars]'))maxAutoStars=Number(input.value);selectChanged=true;fingerprint='';render(getSnapshot())})
  // Use pointer capture rather than native HTML dragging: consistent mouse/touch slot targeting.
  root.addEventListener('dragstart',e=>e.preventDefault())
  // The timeline is wider than its window on purpose (a full day of half-hour slots across
  // every stage), so it needs a horizontal scroll — but an ordinary mouse only turns a
  // vertical wheel. Feed that into the timeline's own scroll instead of leaving it to a
  // trackpad swipe or hunting for the thin scrollbar underneath it.
  root.addEventListener('wheel',e=>{const track=(e.target as Element).closest<HTMLElement>('.show-scroll');if(!track||track.scrollWidth<=track.clientWidth)return;track.scrollLeft+=e.deltaY;e.preventDefault()},{passive:false})
  function render(s:Readonly<GameSnapshot>){if(dragging)return;if(!selectChanged&&root.contains(document.activeElement)&&document.activeElement instanceof HTMLSelectElement)return;selectChanged=false;const f=s.festival,start=f.startDay+s.dayPlan.leadDays;if(day<start||day>=start+s.dayPlan.festivalDays)day=start
    const stages=s.buildings.filter(b=>b.kind==='stage'),key=JSON.stringify([f.bookings,f.finished,f.reputation.music,s.money,Math.floor(s.minute/30),s.day,s.dayPlan,stages.map(b=>[b.id,b.stageDesign?.name]),day,duration,selected,moving,f.musicBase,starTab,minAutoStars,maxAutoStars,f.headlinerPool]);if(key===fingerprint)return;fingerprint=key
    const mix=expectedMusicMix(f),chosen=f.bookings.find(b=>b.id===moving),booked=new Set(f.bookings.map(b=>b.bandId)),available=BANDS.filter(b=>!booked.has(b.id)&&(starTab===0||bandStarRating(b)===starTab))
    if(!chosen&&!available.some(b=>b.id===selected))selected=available[0]?.id??BANDS[0]!.id
    const selectedBand=BANDS.find(b=>b.id===(chosen?.bandId??selected))!
    // A same-genre-affinity clash sharing the same time window, on any given day.
    const clashes=(dayIndex:number,booking:{id:string;start:number;duration:number;bandId:string})=>f.bookings.some(other=>other.id!==booking.id&&other.day===dayIndex&&other.start<booking.start+booking.duration&&booking.start<other.start+other.duration&&genreAffinity(bandGenre(other.bandId),bandGenre(booking.bandId))>=.7)
    const legend=GENRES.map(g=>`<span><i style="background:${g.color}"></i>${g.name}</span>`).join('')
    const dayChips=Array.from({length:s.dayPlan.festivalDays},(_,i)=>{const d=start+i,bookingsForDay=f.bookings.filter(b=>b.day===d),dots=Array.from({length:4},(_,q)=>{const qStart=q*(DAY_MINUTES/4),qEnd=qStart+DAY_MINUTES/4,overlapping=bookingsForDay.filter(b=>b.start<qEnd&&b.start+b.duration>qStart);return `<i class="${overlapping.length?overlapping.some(b=>clashes(d,b))?'warn':'fill':''}"></i>`}).join('');return `<button type="button" class="daychip" data-plan-day-chip="${d}" aria-pressed="${day===d}">${t`Tag ${i+1}`}<div class="dots">${dots}</div></button>`}).join('')
    const cards=available.map(b=>{const genre=bandGenre(b.id),color=GENRES.find(g=>g.id===genre)!.color,appeal=GENRES.reduce((n,g)=>n+mix[g.id]*genreAffinity(g.id,genre),0),stars=bandStarRating(b),fiveStarBlocked=isFiveStarBand(b)&&!(f.headlinerPool??[]).includes(b.id),reason=f.finished?t('Nächste Ausgabe zuerst vorbereiten'):!stages.length?t('Zuerst eine Bühne bauen'):fiveStarBlocked?t('Diese 5-Sterne-Band steht in dieser Planung nicht zur Verfügung'):f.reputation.music<b.reputation?t`Musikruf ${b.reputation} erforderlich` :s.money<b.fee?t('Budget zu niedrig'):'';return `<button type="button" data-band-card="${b.id}" class="band-card ${reason?'unavailable':''}" aria-pressed="${!moving&&selected===b.id}" ${reason?'disabled':''} style="--genre:${color}" title="${reason||t('Band auswählen oder auf einen Zeitblock ziehen')}"><div class="band-card-row"><div class="band-card-main"><strong>${b.name}</strong><small>${'★'.repeat(stars)}${'☆'.repeat(5-stars)} · ${localize(bandGenreLabel(b))} · ${reason||t`Resonanz ${Math.round(appeal*100)} %`}</small></div><div class="band-card-fee">${formatMoney(b.fee)}</div></div><div class="band-card-detail"><small>${joinParts(t`Zugkraft ${b.draw}`,t`Ruf ${b.reputation}`,t`Boxen ${b.speakers}`)}</small><div class="band-affinity">${GENRES.map(g=>`<span title="${g.name}: ${t`${Math.round(genreAffinity(g.id,genre)*100)} % Gefallen`}"><i style="height:${Math.max(4,genreAffinity(g.id,genre)*28)}px;background:${g.color}"></i><small>${g.name}</small></span>`).join('')}</div></div></button>`}).join('')||`<p class="festival-empty">${t('Alle verfügbaren Bands sind bereits gebucht.')}</p>`
    const ruler=`<div class="show-row show-ruler-row"><div class="show-stage ruler-spacer"></div><div class="show-track show-ruler">${Array.from({length:12},(_,i)=>`<div>${String(i*2).padStart(2,'0')}:00</div>`).join('')}</div></div>`
    const timeline=stages.map((stage,index)=>{const bookings=f.bookings.filter(b=>b.stageId===stage.id&&b.day===day),nowPct=day===s.day?s.minute/DAY_MINUTES*100:null;return `<div class="show-row"><div class="show-stage">${esc(stageName(stage,index))}<small>${stage.x}, ${stage.z}</small></div><div class="show-track">${nowPct===null?'':`<div class="now-line" style="left:${nowPct}%"></div>`}${Array.from({length:SLOT_COUNT},(_,i)=>{const minute=i*SLOT_MINUTES,closed=!bookingHoursOpen(s,minute,SLOT_MINUTES),blocked=closed||day*1440+minute<=festivalTime(s)||f.finished;return `<button type="button" class="show-slot ${closed?'closed':''}" data-slot="${esc(stage.id)}" data-start="${minute}" ${blocked?'disabled':''} aria-label="${esc(stageName(stage,index))}, ${clock(minute)}${closed?` ${t('geschlossen')}`:''}" title="${joinParts(clock(minute),closed&&t('geschlossen'))}"></button>`}).join('')}${bookings.map(b=>{const band=BANDS.find(x=>x.id===b.bandId)!,color=GENRES.find(g=>g.id===bandGenre(b.bandId))!.color,conflict=clashes(day,b),error=showIssue(s,b),future=b.day*1440+b.start>festivalTime(s),left=b.start/DAY_MINUTES*100,width=b.duration/DAY_MINUTES*100;return `<button type="button" class="show-booking ${conflict?'conflict':''}" data-booking-card="${esc(b.id)}" draggable="${future}" ${future?'':'disabled'} style="left:${left}%;width:${width}%;--genre:${color}" title="${joinParts(esc(band.name),`${clock(b.start)}–${clock(b.start+b.duration)}`,conflict&&t('Ähnliche Genres gleichzeitig'),error&&esc(localize(error)))}"><strong>${band.name}</strong><small>${clock(b.start)}–${clock(b.start+b.duration)}</small><small>${conflict?`⚠ ${t('Publikum geteilt')}`:band.genre}</small></button><span class="show-changeover" style="left:${left+width}%;width:${Math.min(30,DAY_MINUTES-b.start-b.duration)/DAY_MINUTES*100}%" title="${t('30 Minuten Umbau')}"></span>`}).join('')}</div></div>`}).join('')
    const oldTrack=root.querySelector('.show-scroll'),oldPalette=root.querySelector('.band-palette'),trackLeft=oldTrack?.scrollLeft??0,trackTop=oldTrack?.scrollTop??0,paletteTop=oldPalette?.scrollTop??0
    const cancellable=chosen&&chosen.day*1440+chosen.start>festivalTime(s)
    const autoLocked=f.finished||!stages.length?'disabled':'',timelineStyle=stages.length?'':'style="min-width:0"'
    const picked=moving?t`Verschieben: ${selectedBand.name}`:t`Gewählt: ${selectedBand.name}`
    root.innerHTML=`<div class="planner-controls"><div class="planner-star-tabs">${[0,1,2,3,4,5].map(n=>`<button type="button" data-star-tab="${n}" aria-pressed="${starTab===n}">${n===0?t('Alle'):`${n} ★`}</button>`).join('')}</div><label>${t('Auftrittsdauer')}<select data-plan-duration>${[60,90,120].map(n=>`<option ${duration===n?'selected':''}>${n}</option>`).join('')}</select></label><label>${t('Auto min')}<select data-auto-min-stars>${[1,2,3,4,5].map(n=>`<option value="${n}" ${minAutoStars===n?'selected':''}>${n} ★</option>`).join('')}</select></label><label>${t('Auto max')}<select data-auto-max-stars>${[1,2,3,4,5].map(n=>`<option value="${n}" ${maxAutoStars===n?'selected':''}>${n} ★</option>`).join('')}</select></label><button type="button" data-auto-lineup ${autoLocked} title="${t('Füllt alle noch freien Festivalslots mit passenden, noch verfügbaren Bands. Vorhandene Buchungen bleiben.')}">${t('Leere Slots automatisch füllen')}</button><strong>${picked}</strong>${moving?`<button data-cancel-move>${t('Verschieben beenden')}</button>${cancellable?`<button data-cancel-booking="${esc(chosen.id)}">${joinParts(t('Stornieren'),t`${formatMoney(Math.round(chosen.fee/2))} zurück`)}</button>`:''}`:''}</div><div class="daystrip">${dayChips}</div><div class="genre-legend">${legend}</div><p>${t('Band auf einen Zeitblock ziehen oder Band und anschließend Startzeit anklicken. Alternativ füllt der Automatikmodus die leeren Slots aller Festivaltage. Bereits gebuchte Bands stehen nicht mehr in der Bibliothek. Schraffiert: Umbau; dunkel: laut Tagesplan geschlossen; goldene Linie: aktuelle Uhrzeit.')}</p><div class="planner-board"><div class="band-palette" aria-label="${t('Bandbibliothek')}">${cards}</div><div class="show-scroll"><div class="show-timeline" ${timelineStyle}>${stages.length?ruler:''}${timeline||`<p class="festival-empty">${t('Baut eine Bühne, um Zeitblöcke zu planen. Das Publikum könnt ihr bereits oben vergleichen.')}</p>`}</div></div></div><p>${t('Resonanz = Geschmackspassung der erwarteten Gäste, keine Besucherzahl. Farbbalken zeigen das Gefallen der acht Musikgruppen. Ähnliche Genres gleichzeitig teilen sich ihr Publikum; unterschiedliche Genres verteilen Gäste auf mehrere Bühnen.')}</p>`
    const track=root.querySelector('.show-scroll')!,palette=root.querySelector('.band-palette')!;track.scrollLeft=trackLeft;track.scrollTop=trackTop;palette.scrollTop=paletteTop
  }
  return {render}
}
